# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  dockerhub:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub with access token
        uses: docker/login-action@v2
        with:
          # https://hub.docker.com/settings/security
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: comicrelief/docker-node-sls-2
        flavor: |
          latest=auto
        tags: |
          type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
